dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.7-dev"
  - "3.8-dev"
install:
  - python -m pip install -r requirements.txt
  - python -m pip install --upgrade coveralls coverage
script:
  - coverage run --source kutana -m unittest discover -s test/
after_success:
  - coveralls
deploy:
  provider: pypi
  user: "michaelkrukov"
  password:
    secure: SmWmi3Y/EIxMTpQhMSDoamIq5cmh6RN21bzeRJz3W+GE/3Sbrwv9Q/DKGeihOBmZIelvbOMZ01V7/pbZqdAmtOzM3dQD/29zVDeyYq+RoefYaDziw+tyMMwRSsg+FfKEwlpnOa8WVU8SvNoP5D099WWFywFBk/xQ6chYGdsUEy0RHLrTfMxcii9Ae+isdyqkL0JDKziG2Pad0dRkMg3E10tTvCl7UTQDSzvRwH+9OVCgMT/U72AL9GQ1KEzoNFk7jCgC/1vp15mpQEsKkq5pCag4iWMVPw5kbZb1hSxrVh+uXGPAphuXAMvnetbmxDopaE2AVzV9cwjXc850Ch+rHCQFobkCKQR4/iTEqVwYYXKfUr9gNoy3VcfNfJuKqaifT9Gz62jMFMoui4SIb0yWEf/RImROAGpu+3/ghYUzWVSGj/URZeqL/PwICHrdNnRZCaW6FV55m2Vo4qhHP3DKgEQ2A6AyU8SEQrPAV1/xS4RE7PdMkJT3PK/uZL0W7mMq8tkLh6yjsHm4h7qudwRwAYnTPF34glfItuFa+L/5rpW3JnDxllprr5GtXVe6tyfthaZYdNJc9nqK7aYqln5S2etcJPkABWL7pmEpSuaV9Jv0fqonXquTTXOYN06QhP794bhy5ihYx5WHEzBOCvvnrp8X1xbiBDAcJvZET5AAQCg=
  skip_existing: true
  on:
    tags: true
    branch: master
